In [1]:
import pandas as pd

# Load datasets
patient_df = pd.read_csv("Patient_Data.csv")
billing_df = pd.read_csv("Billing_Data.csv")

# Display the datasets
print("Patient Dataset:")
display(patient_df)

print("\nBilling Dataset:")
display(billing_df)

Patient Dataset:

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

Billing Dataset:

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [2]:
# Merge patient and billing datasets using PatientID
merged_df = pd.merge(
    patient_df,
    billing_df,
    on="PatientID",
    how="left"
)

print("Merged Dataset:")
display(merged_df)

Merged Dataset:

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45,1000,4000
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00,2000,3000

In [3]:
# New patient records
new_patient_records = pd.DataFrame({
    "PatientID": [107, 108],
    "Name": ["George", "Helen"],
    "Department": ["Cardiology", "Neurology"],
    "Doctor": ["Dr. Smith", "Dr. John"],
    "BillAmount": [5800, 6900],
    "ReceptionistID": [2, 3],
    "CheckInTime": ["2023-01-16 09:30", "2023-01-17 10:15"]
})

# Concatenate row-wise
patient_updated = pd.concat(
    [patient_df, new_patient_records],
    ignore_index=True
)

print("Patient Dataset after adding new records:")
display(patient_updated)

Patient Dataset after adding new records:

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
6,107,George,Cardiology,Dr. Smith,5800.0,2,2023-01-16 09:30
7,108,Helen,Neurology,Dr. John,6900.0,3,2023-01-17 10:15

In [4]:
# New billing category columns
new_billing_categories = pd.DataFrame({
    "BillingCategory": [
        "Premium",
        "Standard",
        "Premium",
        "Standard",
        "Basic"
    ],
    "PaymentStatus": [
        "Paid",
        "Paid",
        "Pending",
        "Paid",
        "Pending"
    ]
})

# Concatenate columns-wise
billing_updated = pd.concat(
    [billing_df, new_billing_categories],
    axis=1
)

print("Billing Dataset after adding new columns:")
display(billing_updated)

Billing Dataset after adding new columns:

   PatientID  InsuranceCovered  FinalAmount BillingCategory PaymentStatus
0        101              2000         3000         Premium          Paid
1        102              1500         3500        Standard          Paid
2        103              2500         5000         Premium       Pending
3        104              3000         3200        Standard          Paid
4        105              1000         4000           Basic       Pending